version: '3.8'
services:
  app:
    container_name: web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Changed to use port 8080 externally
    networks:
      - app_network
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    command: [nginx-debug, '-g', 'daemon off;']
  
  db:
    container_name: postgres_db
    image: postgres:15
    platform: linux/arm64/v8
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
  
volumes:
  postgres_data:
  nginx_logs:
