name: CI/CD Pipeline
# ... (previous parts remain the same)

    - name: Setup SSH and Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # ... (previous SSH setup remains the same)
        
        echo "Starting application using Docker Compose..."
        ssh -i ~/.ssh/deploy_key "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" '
        cd /app
        DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 docker-compose up -d --build
        
        # Wait for services to start
        echo "Waiting for services to start..."
        sleep 30
        
        # Check all container statuses
        echo "Checking container statuses..."
        docker-compose ps
        
        # Check nginx container specifically
        echo "Checking nginx logs..."
        docker-compose logs nginx
        
        # More detailed verification
        echo "Performing detailed service verification..."
        if docker-compose ps | grep "nginx" | grep -q "Up"; then
          echo "Nginx service is running"
        else
          echo "Nginx service is not running. Checking for errors..."
          docker-compose logs nginx
          docker-compose ps
          exit 1
        fi
        
        # Check if port 80 is being listened to
        echo "Checking port 80..."
        if netstat -tuln | grep -q ":80 "; then
          echo "Port 80 is being listened to"
        else
          echo "Port 80 is not being listened to. Checking for conflicts..."
          sudo lsof -i :80
          exit 1
        fi
        
        # Verify nginx configuration
        echo "Verifying nginx configuration..."
        docker-compose exec -T nginx nginx -t || {
          echo "Nginx configuration test failed"
          exit 1
        }
        
        # Check actual HTTP response
        echo "Checking HTTP response..."
        curl -I http://localhost || {
          echo "Could not get HTTP response from nginx"
          exit 1
        }
        '
        
    - name: Send Deployment Status Email
      if: always()
      # ... (email notification remains the same)
