name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: |
        npm run build
        ls -la dist/
    
    - name: Setup SSH and Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        # Debug environment (safely)
        echo "Checking environment variables (safely)..."
        if [ -z "$SERVER_IP" ]; then echo "SERVER_IP is not set"; exit 1; fi
        if [ -z "$SERVER_USER" ]; then echo "SERVER_USER is not set"; exit 1; fi
        if [ -z "$DEPLOY_KEY" ]; then echo "DEPLOY_KEY is not set"; exit 1; fi
        
        # Setup SSH with verbose output
        echo "Setting up SSH..."
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/deploy_key
        
        # Debug SSH key (safely)
        echo "Checking SSH key..."
        if ! grep -q "BEGIN" ~/.ssh/deploy_key; then
          echo "SSH key does not contain BEGIN marker"
          exit 1
        fi
        if ! grep -q "END" ~/.ssh/deploy_key; then
          echo "SSH key does not contain END marker"
          exit 1
        fi
        
        # Add server to known hosts
        echo "Adding server to known hosts..."
        ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
        
        # Test SSH connection with debugging
        echo "Testing SSH connection..."
        ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" 'echo "SSH connection test successful"'
        
        # If we get here, SSH is working
        echo "SSH connection successful, proceeding with deployment..."
        
        # Create directory structure on server
        ssh -i ~/.ssh/deploy_key "$SERVER_USER@$SERVER_IP" '
          mkdir -p /app/dist
          sudo chown -R $USER:$USER /app
        '
        
        # Show local files
        echo "Local files:"
        ls -la
        
        # Copy files
        echo "Copying configuration files..."
        scp -v -i ~/.ssh/deploy_key \
          docker-compose.yml \
          Dockerfile \
          nginx.conf \
          init.sql \
          .env \
          package.json \
          package-lock.json \
          "$SERVER_USER@$SERVER_IP:/app/"
        
        # Copy dist directory
        echo "Copying dist directory..."
        if [ -d "dist" ]; then
          scp -v -i ~/.ssh/deploy_key -r \
            dist/* \
            "$SERVER_USER@$SERVER_IP:/app/dist/"
        else
          echo "dist directory not found!"
          exit 1
        fi
        
        # Deploy
        echo "Starting deployment..."
        ssh -i ~/.ssh/deploy_key "$SERVER_USER@$SERVER_IP" '
          cd /app
          docker-compose down
          docker-compose up --build -d
        '

    - name: Send Deployment Status Email
      if: always()
      run: |
        if [ -n "$RESEND_API_KEY" ]; then
          curl -X POST \
          -H "Authorization: Bearer $RESEND_API_KEY" \
          -H "Content-Type: application/json" \
          https://api.resend.com/emails \
          -d '{
            "from": "notifications@hassan-adam.com",
            "to": "haskhr@hotmail.com",
            "subject": "Deployment Status: ${{ job.status }}",
            "html": "Deployment Status: ${{ job.status }}<br>Repository: ${{ github.repository }}<br>Commit: ${{ github.sha }}<br>Triggered by: ${{ github.actor }}"
          }'
        else
          echo "RESEND_API_KEY not set, skipping email notification"
        fi
