name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Build Docker Compose
      run: docker-compose build
      
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Copy docker-compose and related files
        scp -i deploy_key -o StrictHostKeyChecking=no \
          docker-compose.yml \
          Dockerfile \
          nginx.conf \
          init.sql \
          .env \
          $SERVER_USER@$SERVER_IP:/app/
          
        # Copy the built application
        scp -i deploy_key -o StrictHostKeyChecking=no -r \
          dist/* \
          $SERVER_USER@$SERVER_IP:/app/dist/
          
        # Execute deployment commands on the server
        ssh -i deploy_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP '
          cd /app
          docker-compose down
          docker-compose up -d
        '
        
    - name: Send Email Notification
      if: always()
      uses: resend/resend-action@v0.1.0
      with:
        api-key: ${{ secrets.RESEND_API_KEY }}
        from: 'notifications@yourdomain.com'
        to: 'haskhr@hotmail.com'
        subject: 'Deployment Status: ${{ job.status }}'
        body: |
          Deployment Status: ${{ job.status }}
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Triggered by: ${{ github.actor }}
          
          View the deployment logs at:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}